update CMAKE_BUILD_TYPE policy
mathLab/deal2lkit pull request #338
Opened 2016-09-21 10:26 UTC by asartori86

update required for 
https://github.com/dealii/dealii/pull/3136/files

2016-09-21 14:14 UTC, asartori86 commented
@luca-heltai could you please check what is wrong with docker for the debug version?

I cannot understand the issue. Thanks

2016-09-26 14:57 UTC, luca-heltai commented
I think the issue is related to the fact that the latest docker images are broken. I'm recompiling the whole thing right now...

2016-09-30 04:55 UTC, tamiko requested changes
Only the `SET` statement is necessary, no need for the `IF`-`ELSE` block.

2016-09-30 04:55 UTC, tamiko commented on CMakeLists.txt
> +ENDIF()
There is no need for the `IF`-`ELSE` block here. You can simply set unconditionally
```
SET(CMAKE_BUILD_TYPE ${DEAL_II_BUILD_TYPE} CACHE STRING 
  "Choose the type of build, options are: Debug, Release or DebugRelease"
  )
```

If the variable `CMAKE_BUILD_TYPE` is already set in cache, the `SET(... CACHE ...)` function will not override it.
(If no additional `FORCE` is supplied as keyword.)

2016-10-07 10:34 UTC, asartori86 commented on CMakeLists.txt
> +ENDIF()
Oh yes! thanks indeed @tamiko!

2016-11-10 16:16 UTC, asartori86 commented
to me this is ready to be merged. all the tests work fine (except those referenced in #296)

2016-11-11 10:24 UTC, asartori86 commented
I merge this and open an issue that travis is broken

2016-11-11 10:24 UTC, merged