Fixed template problem for hyper ball
mathLab/deal2lkit pull request #370
Opened 2018-03-05 16:06 UTC by GivAlz

In the end I believe this is the best way to maintain compatibility with both old and new versions of the library, at least for HyberBall (but it should be thoroughly tested).

I'll now try to fix the pointer problem!

2018-03-05 16:31 UTC, GivAlz commented
Fixing the other problem is easier than I thought...I shall soon update this PR.

Still there's three warnings about some deprecated grids (cylindricalboundary, coneboundary, halfhypershellball, hyperballboundary).

2018-03-05 20:17 UTC, luca-heltai commented
This PR is not compiling. Not on my machine, and not on travis...

2018-03-05 20:17 UTC, luca-heltai requested changes

2018-03-05 20:17 UTC, luca-heltai commented on source/parsed_finite_element.cc
> +  return FETools::get_fe_by_name<dim,spacedim>(fe_name).get();
The correct approach is the other way around. Make this function return a unique ptr.

2018-03-05 22:13 UTC, GivAlz commented
Look at line 593 of the travis output, it states that I'm trying to use the "get" method on a pointer of type `dealii::FiniteElement<1, 1>*`:

`
../source/parsed_finite_element.cc:69:57: error: request for member ‘get’ in ‘dealii::FETools::get_fe_by_name<1, 1>(((const deal2lkit::ParsedFiniteElement<1, 1>*)this)->deal2lkit::ParsedFiniteElement<1, 1>::fe_name)’, which is of pointer type ‘dealii::FiniteElement<1, 1>*’ (maybe you meant to use ‘->’ ?)
`

But with the last deal.ii dev that is not the case anymore, it is a very recent change:
`
Changed: FETools::get_fe_by_name returns a std::unique_ptr instead of a owning raw pointer to prevent creating memory leaks.
(Daniel Arndt, 2018/02/09)
`

(and in fact on my machine it compiles and I also ran 60 tests or so and they were fine)

I don't know if it is possible to make it work in both cases; is there a way to make it compile in both cases using a macro and an if statement? I tried to look for something but the best thing I can think of is using a flag which is passed if we want to compile for the development version.

2018-03-05 22:19 UTC, luca-heltai commented
The comment above remains. If you use `get()` on a unique pointer, you are asking for troubles. The unique pointer is destroyed once it gets out of scope. In your case, right at the end of the function. You should modify deal2lkit to return a unique pointer instead of a pointer in the `operator()()`.

We should update the dealii image on docker with the latest release. I'll try to do this tomorrow.

2018-03-05 22:21 UTC, luca-heltai commented
We don't want to make it compile in both cases. deal2lkit has a tag 8.5.1 that should be used with deal.II 8.5.1. The development version should compile with the development version of deal.II. No ifdefs/defines/etc.

2018-03-06 09:20 UTC, GivAlz commented
Ok, I didn't know so much troubles could come out of the get method...I'll fix it :)

2018-03-06 13:25 UTC, luca-heltai commented
Do you have `numdiff` installed? If not, you should install numdiff. This will take care of numerical roundoff errors.

The trouble is in the fact that unique_ptr destroy the pointer when they get destroyed. That's the all point of unique_pointers. If you issue a `get()` on the unique pointer, and right afterward you exit the function where the unique pointer is created, you destroy the object pointed to.

2018-03-06 15:20 UTC, GivAlz commented
So, numdiff was one of the problems. Some tests are still failing, I guess there's some problem with the parameters...
`
The following tests FAILED:
	127 - parameter_acceptor/parameter_acceptor_10.debug (Failed)
	128 - parameter_acceptor/parameter_acceptor_10.release (Failed)
	139 - parsed_data_out/parsed_data_out_03.debug (Failed)
	140 - parsed_data_out/parsed_data_out_03.release (Failed)
	141 - parsed_data_out/parsed_data_out_04.debug (Failed)
	142 - parsed_data_out/parsed_data_out_04.release (Failed)
	167 - parsed_finite_element/parsed_finite_element_01.debug (Failed)
	168 - parsed_finite_element/parsed_finite_element_01.release (Failed)
	169 - parsed_finite_element/parsed_finite_element_02.debug (Failed)
	170 - parsed_finite_element/parsed_finite_element_02.release (Failed)
	211 - parsed_manifold/parsed_manifold_01.debug (Failed)
	212 - parsed_manifold/parsed_manifold_01.release (Failed)
	213 - parsed_manifold/parsed_manifold_02.debug (Failed)
	214 - parsed_manifold/parsed_manifold_02.release (Failed)
	217 - parsed_manifold/parsed_manifold_04.debug (Failed)
	218 - parsed_manifold/parsed_manifold_04.release (Failed)
	221 - parsed_manifold/parsed_manifold_06.debug (Failed)
	222 - parsed_manifold/parsed_manifold_06.release (Failed)
Errors while running CTest
`

2018-03-14 09:30 UTC, merged